### ISSUE TITLE
Disabled output formats are still used when extension is specified

### ISSUE THREAD

**Issue by clayhinson** [frapi/frapi#108] opened 2012-03-03 04:47 UTC
For example, disabling XML output in the Admin console does not prevent XML from being output on requesting http://api.frapi/resource.xml

Not sure if this should return the default format or 404.

**Comment by dshafik** [comment] 2012-03-03 06:13
This should be a `412 Precondition Failed`; the same as when we cannot satisfy the `Accept` header — given that we're using the extensions as a poor mans `Accept` header. 

Using a 404 for something like: `/resource/:id.xml` makes it awkward to figure out if `:id` is not found, or if the format is not found.

**Comment by clayhinson** [comment] 2012-03-03 06:37
agreed - 412 it is.

**Comment by dshafik** [comment] 2012-03-31 04:30
I actually can't reproduce this... but I can reproduce #120 which might be the issue here? Essentially, Accept mimetypes would cause frapi to output any format, even if it was disabled.

**Comment by clayhinson** [comment] 2012-04-20 13:24
#129 didn't fix this issue - I can still request http://api.frapi/action.xml and receive an XML document, even with XML output disabled.

**Comment by trevormorse** [comment] 2012-06-14 03:40
I can recreate the issue that @clayhinson is seeing. It has to do with the way FRAPI is caching the formats-enabled. It is not checking the enabled element of each format before storing it as enabled. I have a fix for this part done and ready to go. However once my fix is in place HTTP Digest fails, and on public actions the data is returned in JSON (the default output) instead of a 412. So still needs some work :-)

**Comment by dshafik** [comment] 2012-06-27 02:59
Fixed by #172

**Closed as completed by dshafik** 2012-06-27 02:59 UTC
