### ISSUE TITLE
Error Creating Partners

### ISSUE THREAD

**Issue by vinay035** [frapi/frapi#153] opened 2012-05-23 16:25 UTC
I have 2 amozon instances in 1 the site will be hosted and in other the frapi will be hosted.Now i will create the developer account in my site and it must also create a partner in frapi also.
i tried using CLI to  create partners. i also tried to edit the partners.xml to add new partner but no luck.
Please guide me how to tackle this issue.

**Comment by trevormorse** [comment] 2012-06-13 16:35
Hi There,

FRAPI caches all of it's setting in APC by default, or whatever caching mechanism you set. 

The problem with APC is that apache/php and CLI/php use different caches as they are separate processes. So the frapi CLI unfortunately cannot change the cache for FRAPI running in apache. The same is most likely the problem with changing the file directly. The file modifications will not get picked up until apache is restarted (therefore apc being cleared) or a force flush from the FRAPI admin interface.

One approach you could use is to create an action in your frapi install that clears the apc key for partners after adding a new partner. This could then be called from your site code.

Hope that helps.

**Comment by dshafik** [comment] 2012-06-27 03:19
This should be caused by the caching FRAPI has in place (which is cleared when you restart your web server, or click "Sync" in FRAPI). This is intended behavior — a better option is to not use the built-in FRAPI partners auth, and to instead   authenticate on your own. By doing this you can authenticate against a database or some such, including the same database used by the website.

I'm going to close this issue as it's not a bug.

**Closed as completed by dshafik** 2012-06-27 03:19 UTC
