### ISSUE TITLE
Index bug in Introduction.html.tpl 

### ISSUE THREAD

**Issue by muldos** [frapi/frapi#186] opened 2012-07-16 13:48 UTC
After creating a custom action, the links on the documentation page are broken (they dont expand the div containing the doc).
I investigated a bit and found a bug : 
at line 323 of Introduction.html.tpl, the variable $params is used instead of $subparam.

``` php
 <td><?php echo $param['name']; ?></td>
```

must be replaced with 

``` php
 <td><?php echo $subparam['name']; ?></td>
```

Hope it helps improve this great framework !!

Thanks for your awesome work,

David

**Comment by davidcoallier** [comment] 2012-07-16 16:07
@trevormorse This is related to a bugfix you made lately isnt' it?

**Comment by trevormorse** [comment] 2012-07-18 12:28
Yes, this is a duplicate of issue #180.

**Closed as completed by trevormorse** 2012-07-18 12:28 UTC

**Comment by mapirelli** [comment] 2012-12-11 13:12
This issue was not resolved in the right way.

This is the right from line 304 of Introduction.html.tpl

<?php
                                    foreach ($action['parameters'] as $key => $param) {
                                        if (is_array($param) && isset($param[0])) {
                                            foreach ($param as $subkey => $subparam) {
                                                ?>
                                                <tr>
                                                    <td class="param-name"><?php echo $subparam['name'] ?></td>
                                                    <td class="param-required">
                                                        <?php
                                                            echo isset($subparam['required']) && $subparam['required'] == '1'
                                                                ? '<strong>&#10003;</strong>' : '<strong>&#10007;</strong>'
                                                        ?>
                                                    </td>
                                                </tr>
                                                <?php
                                            }
                                        } else {
                                        ?>
                                        <tr>
                                            <td><?php echo $param['name']; ?></td>
                                                <td class="param-required">
                                                    <?php
                                                        echo isset($param['required']) && $param['required'] == '1'
                                                        ? '<strong>&#10003;</strong>' : '<strong>&#10007;</strong>'
                                                    ?>
                                                </td>
                                        </tr>
                                        <?php 
                                        }
                                    }
                                    ?>

**Comment by trevormorse** [comment] 2012-12-11 13:23
@mapirelli This has been fixed but not merge in yet. You can see the pull request that looks a lot like your code in pull request #181
